package com.example.mini_project_grah

object dataMahasiswa {
    var arrMahasiswa = arrayOf(
        bankMahasiswa("Alvin Kurniawan", "160423055", "DSAI", R.drawable.alvin, "Seorang mahasiswa yang sedang menempuh tahun kedua pendidikannya di Universitas Surabaya. Anak ini sangat tertarik dengan Matematika, yang akhirnya membuat dia masuk ke Teknik Informatika dan memilih program studi Data Science & Artificial Intelligence", "*) Big Data Analytics\n*) Intelligent Information Retrieval\n*) Machine Learning\n*) Numerical Methods\n*) Native Mobile Programming", "*) Asisten Dosen Mathematics Semester Genap 2024/2025\n*) Asisten Magang Algorithm & Programming Semester Ganjil 2025/2026\n*) Back-End Developer for Industrial Games XXXIII"),
        bankMahasiswa("Richie Viriyananda", "160423078", "IMES", R.drawable.richie, "Seorang mahasiswa yang sedang menempuh tahun kedua pendidikannya di Universitas Surabaya. Anak ini sangat tertarik dengan Database, yang akhirnya membuat dia masuk ke Teknik Informatika dan memilih program studi Information Management & Enterprise System", "*) Business Geography\n*) SCM Accounting System\n*) Machine Learning\n*) Numerical Methods\n*) Native Mobile Programming", "*) Anggota Bidang CDD KSM Informatika 2024/2025\n*) Wirausahawan Pudding\n*) Driver Gojek"),
        bankMahasiswa("Harren Anwar Wijaya", "160423081", "GD", R.drawable.harren, "Seorang mahasiswa yang sedang menempuh tahun kedua pendidikannya di Universitas Surabaya. Anak ini sangat tertarik dengan Rainbow Six Siege, yang akhirnya membuat dia masuk ke Teknik Informatika dan memilih program studi Game Development", "*) Tabletop Game Design\n*) AI in Game Design\n*) Machine Learning\n*) Numerical Methods\n*) Native Mobile Programming", "*) Koor Bidang Dhamma UKKB Universitas Surabaya\n*) Bendahara UKKB Universitas Surabaya\n*) Pro Player Rainbow Six Siege"),
        bankMahasiswa("Ericko Sutanto", "160423088", "NCS", R.drawable.ericko, "Seorang mahasiswa yang sedang menempuh tahun kedua pendidikannya di Universitas Surabaya. Anak ini sangat tertarik dengan dunia Cyber, yang akhirnya membuat dia masuk ke Teknik Informatika dan memilih program studi Network & Cyber Security", "*) Internet of Things\n*) Cryptography\n*) Machine Learning\n*) Numerical Methods\n*) Native Mobile Programming", "*) Anggota Loyal Capture the Flag (CTF)\n*) Pro Player Bee Swarm Simulator\n*) Pro Player Fish It!"),
        bankMahasiswa("Jonathan Andrian", "160423095", "DMT", R.drawable.jonathan, "Seorang mahasiswa yang sedang menempuh tahun kedua pendidikannya di Universitas Surabaya. Anak ini sangat tertarik dengan Fotografi & Cinematografi, yang akhirnya membuat dia masuk ke Teknik Informatika dan memilih program studi Digital Media Technology", "*) Cinematography\n*) Design & Photography\n*) Machine Learning\n*) Numerical Methods\n*) Native Mobile Programming", "*) Anggota UKM Catur Universitas Surabaya\n*) Anggota Loyal Competitive Programming (CP)\n*) Pro Player Mobile Legends: Bang Bang")
    )
}